spring:
  elasticsearch:
    uris: 127.0.0.1:9200
    username: elastic
    password: Q2i6oixj5uF=UL8yq7z1
  ai:
    alibaba:
      toolcalling:
        tavilysearch:
          api-key: ${TAVILY_API_KEY}
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: spring-ai-demo-index
        dimensions: 1024
        similarity: cosine
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
server:
  port: 8081