spring:
  application:
    name: graph-demo
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
server:
  port: 8081

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0 # 全量采样
#  otlp:
#    tracing:
#      # SkyWalking OAP 的地址
#      endpoint: http://127.0.0.1:11800
#      transport: grpc
#  observations:
#    key-values:
#      application: ${spring.application.name}