spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Zhouyu123456...
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      #      base-url: https://api.deepseek.com   # 如果使用DeepSeek则设置这个base-url
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3-max
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

server:
  port: 8081